name = "NMFMerge"
uuid = "9cc52eda-dfaf-4e21-aae3-9f26bed153a3"
authors = ["youdongguo <1010705897@qq.com> and contributors"]
version = "1.0.0-DEV"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
DataStructures = "0.18"
ForwardDiff = "0.10"
LinearAlgebra = "1"
NMF = "1"
Test = "1"
julia = "1.10"

[extras]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
NMF = "6ef6ca0d-6ad7-5ff6-b225-e928bfa0a386"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ForwardDiff", "NMF", "Test"]
